import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { prisma } from "../db/client"
export const getServerSideProps = async () => {
  const questions = await prisma.question.findMany()
  return {
    props: {
      questions: JSON.stringify(questions)
    }
  }
}
const Home: NextPage = (props: any) => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <code>
        {props.questions}
      </code>
    </div>
  )
}

export default Home
